import type { TemplateClause, ContractVariable } from '@/types/contract'

export const CONTRACT_VARIABLES: ContractVariable[] = [
  { key: 'landlord_name', label: 'Nombre del arrendador', section: 'parties' },
  { key: 'landlord_cedula', label: 'Cédula del arrendador', section: 'parties' },
  { key: 'landlord_city', label: 'Ciudad de la cédula (arrendador)', section: 'parties' },
  { key: 'landlord_phone', label: 'Celular del arrendador', section: 'parties' },
  { key: 'tenant_name', label: 'Nombre del arrendatario', section: 'parties' },
  { key: 'tenant_cedula', label: 'Cédula del arrendatario', section: 'parties' },
  { key: 'tenant_city', label: 'Ciudad de la cédula (arrendatario)', section: 'parties' },
  { key: 'tenant_phone', label: 'Celular del arrendatario', section: 'parties' },
  { key: 'municipality', label: 'Municipio del contrato', section: 'parties' },
  { key: 'property_type', label: 'Tipo de inmueble', section: 'property' },
  { key: 'property_floor', label: 'Piso del inmueble', section: 'property' },
  { key: 'property_address', label: 'Dirección', section: 'property' },
  { key: 'property_neighborhood', label: 'Barrio', section: 'property' },
  { key: 'property_description', label: 'Descripción interior del inmueble', section: 'property' },
  { key: 'rent_amount_text', label: 'Canon en letras', section: 'financial' },
  { key: 'rent_amount', label: 'Canon en números', section: 'financial' },
  { key: 'bank_name', label: 'Nombre del banco', section: 'financial' },
  { key: 'bank_account', label: 'Número de cuenta', section: 'financial' },
  { key: 'start_date', label: 'Fecha de inicio', section: 'financial' },
  { key: 'end_date', label: 'Fecha de fin', section: 'financial' },
  { key: 'duration_months', label: 'Duración del contrato', section: 'financial' },
  { key: 'max_occupants', label: 'Número máximo de personas', section: 'financial' },
  { key: 'deposit_amount_text', label: 'Fondo de garantía en letras', section: 'financial' },
  { key: 'deposit_amount', label: 'Fondo de garantía en números', section: 'financial' },
  { key: 'signature_city', label: 'Ciudad de firma', section: 'signature' },
  { key: 'signature_day', label: 'Día de firma', section: 'signature' },
  { key: 'signature_month', label: 'Mes de firma', section: 'signature' },
  { key: 'signature_year', label: 'Año de firma', section: 'signature' },
]

export const BASE_CLAUSES: TemplateClause[] = [
  {
    id: 'primera',
    title: 'PRIMERA.- OBJETO DEL CONTRATO',
    content: `El Arrendador, propietario de {{property_type}} en {{property_floor}}, ubicado en la {{property_address}}, barrio {{property_neighborhood}}, del Municipio de {{municipality}}, concede al Arrendatario el uso y goce de la misma en calidad de arriendo de un inmueble de propiedad del Arrendador. {{property_description}}`,
    required: true,
    defaultEnabled: true,
    variables: ['property_type', 'property_floor', 'property_address', 'property_neighborhood', 'municipality', 'property_description'],
  },
  {
    id: 'segunda',
    title: 'SEGUNDA - CANON MENSUAL',
    content: 'El precio mensual que el Arrendatario se obliga a pagar al Arrendador por el uso y goce del inmueble será la suma de: {{rent_amount_text}} PESOS (${{rent_amount}}) los cuales deberán ser cancelados en efectivo{{bank_payment_text}}. Los servicios de energía, tasa de aseo, alumbrado público, agua y alcantarillado, corren por cuenta del Arrendatario. Los servicios se entregan al día y a paz y salvo.',
    required: true,
    defaultEnabled: true,
    variables: ['rent_amount_text', 'rent_amount', 'bank_payment_text'],
  },
  {
    id: 'tercera',
    title: 'TERCERA.- REAJUSTE DEL CANON DE ARRENDAMIENTO',
    content: `El canon podrá ser incrementado de acuerdo a las partes y/o según lo establece la ley.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'cuarta',
    title: 'CUARTA.- OPORTUNIDAD PARA EL PAGO',
    content: `El Arrendatario se obliga a pagar al Arrendador el canon mensual de arrendamiento de manera anticipada de cada mes como producto del presente contrato, so pena de pagar intereses moratorios por los días de retraso en el pago del canon de arriendo al Arrendador, en una cuenta de ahorros {{bank_name}} Nro. {{bank_account}}.`,
    required: true,
    defaultEnabled: true,
    variables: ['bank_name', 'bank_account'],
  },
  {
    id: 'quinta',
    title: 'QUINTA - TÉRMINO',
    content: `El término de duración del presente contrato será de {{duration_months}}, a partir del día {{start_date}} hasta el {{end_date}}.`,
    required: true,
    defaultEnabled: true,
    variables: ['duration_months', 'start_date', 'end_date'],
  },
  {
    id: 'sexta',
    title: 'SEXTA - DESTINACIÓN',
    content: `El Arrendatario se obliga a dar al inmueble uso para vivienda familiar habitada hasta para {{max_occupants}} persona(s) adulta(s) y no podrá darle otro uso, el Arrendatario no podrá subarrendar este inmueble a otra persona natural ni jurídica. El Arrendatario no podrá mantener mascotas, no podrá mantener altos volúmenes de equipo de sonidos y otros que puedan incomodar a los vecinos. No se permite obstaculizar el pasillo y la entrada del edificio a las demás personas. No se permite extender ropa en la fachada del edificio.`,
    required: false,
    defaultEnabled: true,
    variables: ['max_occupants'],
  },
  {
    id: 'septima',
    title: 'SÉPTIMA.- SERVICIOS PÚBLICOS Y PAGO',
    content: `El inmueble consta con servicios de energía eléctrica, acueducto y alcantarillado, en funcionamiento normal.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'octava',
    title: 'OCTAVA.- ESTADO DEL INMUEBLE',
    content: `El Arrendatario declara haber recibido el inmueble objeto de este contrato, junto con los servicios antes descritos en buen estado y en perfecto funcionamiento, y se obliga a devolver el inmueble al Arrendador, a la terminación del contrato en el mismo estado en que lo recibió, tanto de pintura como de aseo y cualquier obstrucción o mal uso en acometidas de aguas, energía y alcantarillado, etc, será de responsabilidad del Arrendatario.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'novena',
    title: 'NOVENA.- REPARACIONES',
    content: `El Arrendatario tendrá a su cargo las reparaciones locativas necesarias a que se refiere la ley (C.C, arts. 2028, 2029 y 2030) y no podrá realizar otras sin el consentimiento escrito del Arrendador.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'decima',
    title: 'DÉCIMA.- TERMINACIÓN DEL CONTRATO',
    content: `Son causales de terminación del contrato las de ley y especialmente: a) No cancelación oportuna por parte del Arrendatario del canon mensual, b) Subarriendo, cesión y cambio de destinación o actividad ilícita del inmueble por parte del Arrendatario, c) construcción, mejoras, ampliaciones e instalaciones que requiera el inmueble por parte del arrendador.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'decima-primera',
    title: 'DÉCIMA PRIMERA: PRÓRROGA',
    content: `El presente contrato se entenderá prorrogado automáticamente por un periodo igual al inicial, si antes de treinta (30) días al vencimiento del presente contrato ninguna de las partes avisa a la otra parte por escrito su intención de darlo por terminado.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'decima-tercera',
    title: 'DÉCIMA TERCERA.- CLÁUSULA PENAL',
    content: `El incumplimiento por cualquiera de las partes de las obligaciones y cláusulas derivadas de este contrato la constituirá en deudora de la otra quien por su parte si cumplió, por la suma de un (1) salario mínimo legal mensual vigente a la fecha del incumplimiento, y sin necesidad de constituir en mora al Arrendatario o a la parte que incumplió a título de pena, sin menoscabo y perjuicio del pago del canon de arrendamiento y de los perjuicios que pudieren ocasionarse.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'decima-cuarta',
    title: 'DÉCIMA CUARTA: MÉRITO EJECUTIVO',
    content: `El presente contrato presta mérito ejecutivo por el incumplimiento total o parcial de cualquiera de las cláusulas aquí estipuladas por parte del ARRENDATARIO, constituyéndose como un documento claro, expreso y exigible, siendo la fecha de exigibilidad la correspondiente al momento en que se configure el incumplimiento.`,
    required: false,
    defaultEnabled: true,
    variables: [],
  },
  {
    id: 'garantia',
    title: 'GARANTÍA',
    content: 'Para efectos de garantizar el aseo, mantenimiento del inmueble y el pago de los servicios públicos domiciliarios que se generen durante la vigencia del contrato, el ARRENDATARIO entrega un fondo de garantía por valor de {{deposit_amount_text}} PESOS (${{deposit_amount}}), el cual no será reembolsable y se destinará exclusivamente a dichos fines.',
    required: false,
    defaultEnabled: true,
    variables: ['deposit_amount_text', 'deposit_amount'],
  },
]
